### PR TITLE
Fixing the quiet option inside `src/CRTM_LifeCycle.f90`

### LINKED ISSUE #78: CRTM unit tests are failing with segmentation fault
The following tests are failing with segmentation fault:

```
The following tests FAILED:
	  4 - Unit_TL_TEST (SEGFAULT)
	 15 - test_forward_Simple_atms_n21 (SEGFAULT)
	 16 - test_forward_Simple_cris-fsr_n21 (SEGFAULT)
	 17 - test_forward_Simple_v.abi_g18 (SEGFAULT)
	 18 - test_forward_Simple_atms_npp (SEGFAULT)
	 19 - test_forward_Simple_cris399_npp (SEGFAULT)
	 20 - test_forward_Simple_v.abi_gr (SEGFAULT)
	 21 - test_forward_Simple_abi_g18 (SEGFAULT)
	 22 - test_forward_Simple_modis_aqua (SEGFAULT)
	 23 - test_forward_AOD_cris-fsr_n21 (SEGFAULT)
	 24 - test_forward_AOD_v.abi_g18 (SEGFAULT)
	 25 - test_forward_AOD_cris399_npp (SEGFAULT)
	 26 - test_forward_AOD_v.abi_gr (SEGFAULT)
	 27 - test_forward_AOD_abi_g18 (SEGFAULT)
	 28 - test_forward_AOD_airs_aqua (SEGFAULT)
	 29 - test_forward_Zeeman_ssmis_f20 (SEGFAULT)
	 30 - test_forward_Zeeman_ssmis_f19 (SEGFAULT)
	 31 - test_forward_Zeeman_ssmis_f18 (SEGFAULT)
	 32 - test_forward_Zeeman_ssmis_f17 (SEGFAULT)
	 33 - test_forward_Zeeman_ssmis_f16 (SEGFAULT)
	 34 - test_forward_ChannelSubset_iasi_metop-b (SEGFAULT)
	 35 - test_forward_ClearSky_atms_n21 (SEGFAULT)
	 36 - test_forward_ClearSky_cris-fsr_n21 (SEGFAULT)
	 37 - test_forward_ClearSky_v.abi_g18 (SEGFAULT)
	 38 - test_forward_ClearSky_atms_npp (SEGFAULT)
	 39 - test_forward_ClearSky_cris399_npp (SEGFAULT)
	 40 - test_forward_ClearSky_v.abi_gr (SEGFAULT)
	 41 - test_forward_ClearSky_abi_g18 (SEGFAULT)
	 42 - test_forward_ClearSky_modis_aqua (SEGFAULT)
	 43 - test_forward_Aircraft_cris-fsr_n21 (SEGFAULT)
	 44 - test_forward_Aircraft_crisB1_npp (SEGFAULT)
	 45 - test_forward_ScatteringSwitch_atms_n21 (SEGFAULT)
	 46 - test_forward_ScatteringSwitch_cris-fsr_n21 (SEGFAULT)
	 47 - test_forward_ScatteringSwitch_v.abi_g18 (SEGFAULT)
	 48 - test_forward_ScatteringSwitch_atms_npp (SEGFAULT)
	 49 - test_forward_ScatteringSwitch_cris399_npp (SEGFAULT)
	 50 - test_forward_ScatteringSwitch_v.abi_gr (SEGFAULT)
	 51 - test_forward_ScatteringSwitch_abi_g18 (SEGFAULT)
	 52 - test_forward_ScatteringSwitch_modis_aqua (SEGFAULT)
	 53 - test_forward_SOI_atms_n21 (SEGFAULT)
	 54 - test_forward_SOI_cris-fsr_n21 (SEGFAULT)
	 55 - test_forward_SOI_v.abi_g18 (SEGFAULT)
	 56 - test_forward_SOI_atms_npp (SEGFAULT)
	 57 - test_forward_SOI_cris399_npp (SEGFAULT)
	 58 - test_forward_SOI_v.abi_gr (SEGFAULT)
	 59 - test_forward_SOI_abi_g18 (SEGFAULT)
	 60 - test_forward_SOI_modis_aqua (SEGFAULT)
	 61 - test_forward_SSU_ssu_n06 (SEGFAULT)
	 62 - test_forward_SSU_ssu_n14 (SEGFAULT)
	 63 - test_forward_VerticalCoordinates_atms_n21 (SEGFAULT)
	 64 - test_forward_VerticalCoordinates_cris-fsr_n21 (SEGFAULT)
	 65 - test_forward_VerticalCoordinates_v.abi_g18 (SEGFAULT)
	 66 - test_forward_VerticalCoordinates_atms_npp (SEGFAULT)
	 67 - test_forward_VerticalCoordinates_cris399_npp (SEGFAULT)
	 68 - test_forward_VerticalCoordinates_v.abi_gr (SEGFAULT)
	 69 - test_forward_VerticalCoordinates_abi_g18 (SEGFAULT)
	 70 - test_forward_VerticalCoordinates_modis_aqua (SEGFAULT)
	 71 - test_k_matrix_Simple_atms_n21 (SEGFAULT)
	 72 - test_k_matrix_Simple_cris-fsr_n21 (SEGFAULT)
	 73 - test_k_matrix_Simple_v.abi_g18 (SEGFAULT)
	 74 - test_k_matrix_Simple_atms_npp (SEGFAULT)
	 75 - test_k_matrix_Simple_cris399_npp (SEGFAULT)
	 76 - test_k_matrix_Simple_v.abi_gr (SEGFAULT)
	 77 - test_k_matrix_Simple_abi_g18 (SEGFAULT)
	 78 - test_k_matrix_Simple_modis_aqua (SEGFAULT)
	 79 - test_k_matrix_AOD_cris-fsr_n21 (SEGFAULT)
	 80 - test_k_matrix_AOD_v.abi_g18 (SEGFAULT)
	 81 - test_k_matrix_AOD_cris399_npp (SEGFAULT)
	 82 - test_k_matrix_AOD_v.abi_gr (SEGFAULT)
	 83 - test_k_matrix_AOD_abi_g18 (SEGFAULT)
	 84 - test_k_matrix_AOD_airs_aqua (SEGFAULT)
	 85 - test_k_matrix_Zeeman_ssmis_f20 (SEGFAULT)
	 86 - test_k_matrix_Zeeman_ssmis_f19 (SEGFAULT)
	 87 - test_k_matrix_Zeeman_ssmis_f18 (SEGFAULT)
	 88 - test_k_matrix_Zeeman_ssmis_f17 (SEGFAULT)
	 89 - test_k_matrix_Zeeman_ssmis_f16 (SEGFAULT)
	 90 - test_k_matrix_ChannelSubset_iasi_metop-b (SEGFAULT)
	 91 - test_k_matrix_ClearSky_atms_n21 (SEGFAULT)
	 92 - test_k_matrix_ClearSky_cris-fsr_n21 (SEGFAULT)
	 93 - test_k_matrix_ClearSky_v.abi_g18 (SEGFAULT)
	 94 - test_k_matrix_ClearSky_atms_npp (SEGFAULT)
	 95 - test_k_matrix_ClearSky_cris399_npp (SEGFAULT)
	 94 - test_k_matrix_ClearSky_atms_npp (SEGFAULT)
	 95 - test_k_matrix_ClearSky_cris399_npp (SEGFAULT)
	 96 - test_k_matrix_ClearSky_v.abi_gr (SEGFAULT)
	 97 - test_k_matrix_ClearSky_abi_g18 (SEGFAULT)
	 98 - test_k_matrix_ClearSky_modis_aqua (SEGFAULT)
	 99 - test_k_matrix_ScatteringSwitch_atms_n21 (SEGFAULT)
	100 - test_k_matrix_ScatteringSwitch_cris-fsr_n21 (SEGFAULT)
	101 - test_k_matrix_ScatteringSwitch_v.abi_g18 (SEGFAULT)
	102 - test_k_matrix_ScatteringSwitch_atms_npp (SEGFAULT)
	103 - test_k_matrix_ScatteringSwitch_cris399_npp (SEGFAULT)
	104 - test_k_matrix_ScatteringSwitch_v.abi_gr (SEGFAULT)
	105 - test_k_matrix_ScatteringSwitch_abi_g18 (SEGFAULT)
	106 - test_k_matrix_ScatteringSwitch_modis_aqua (SEGFAULT)
	107 - test_k_matrix_SOI_atms_n21 (SEGFAULT)
	108 - test_k_matrix_SOI_cris-fsr_n21 (SEGFAULT)
	109 - test_k_matrix_SOI_v.abi_g18 (SEGFAULT)
	110 - test_k_matrix_SOI_atms_npp (SEGFAULT)
	111 - test_k_matrix_SOI_cris399_npp (SEGFAULT)
	112 - test_k_matrix_SOI_v.abi_gr (SEGFAULT)
	113 - test_k_matrix_SOI_abi_g18 (SEGFAULT)
	114 - test_k_matrix_SOI_modis_aqua (SEGFAULT)
	115 - test_k_matrix_SSU_ssu_n06 (SEGFAULT)
	116 - test_k_matrix_SSU_ssu_n14 (SEGFAULT)
	117 - test_k_matrix_VerticalCoordinates_atms_n21 (SEGFAULT)
	118 - test_k_matrix_VerticalCoordinates_cris-fsr_n21 (SEGFAULT)
	119 - test_k_matrix_VerticalCoordinates_v.abi_g18 (SEGFAULT)
	120 - test_k_matrix_VerticalCoordinates_atms_npp (SEGFAULT)
	121 - test_k_matrix_VerticalCoordinates_cris399_npp (SEGFAULT)
	122 - test_k_matrix_VerticalCoordinates_v.abi_gr (SEGFAULT)
	123 - test_k_matrix_VerticalCoordinates_abi_g18 (SEGFAULT)
	124 - test_k_matrix_VerticalCoordinates_modis_aqua (SEGFAULT)
	125 - test_adjoint_Simple_atms_n21 (SEGFAULT)
	126 - test_adjoint_Simple_cris-fsr_n21 (SEGFAULT)
	127 - test_adjoint_Simple_v.abi_g18 (SEGFAULT)
	128 - test_adjoint_Simple_atms_npp (SEGFAULT)
	129 - test_adjoint_Simple_cris399_npp (SEGFAULT)
	130 - test_adjoint_Simple_v.abi_gr (SEGFAULT)
	131 - test_adjoint_Simple_abi_g18 (SEGFAULT)
	132 - test_adjoint_Simple_modis_aqua (SEGFAULT)
	133 - test_adjoint_ClearSky_atms_n21 (SEGFAULT)
	134 - test_adjoint_ClearSky_cris-fsr_n21 (SEGFAULT)
	135 - test_adjoint_ClearSky_v.abi_g18 (SEGFAULT)
	136 - test_adjoint_ClearSky_atms_npp (SEGFAULT)
	137 - test_adjoint_ClearSky_cris399_npp (SEGFAULT)
	138 - test_adjoint_ClearSky_v.abi_gr (SEGFAULT)
	139 - test_adjoint_ClearSky_abi_g18 (SEGFAULT)
	140 - test_adjoint_ClearSky_modis_aqua (SEGFAULT)
	141 - test_tangent_linear_Simple_atms_n21 (SEGFAULT)
	142 - test_tangent_linear_Simple_cris-fsr_n21 (SEGFAULT)
	143 - test_tangent_linear_Simple_v.abi_g18 (SEGFAULT)
	144 - test_tangent_linear_Simple_atms_npp (SEGFAULT)
	145 - test_tangent_linear_Simple_cris399_npp (SEGFAULT)
	146 - test_tangent_linear_Simple_v.abi_gr (SEGFAULT)
	147 - test_tangent_linear_Simple_abi_g18 (SEGFAULT)
	148 - test_tangent_linear_Simple_modis_aqua (SEGFAULT)
	149 - test_tangent_linear_ClearSky_atms_n21 (SEGFAULT)
	150 - test_tangent_linear_ClearSky_cris-fsr_n21 (SEGFAULT)
	151 - test_tangent_linear_ClearSky_v.abi_g18 (SEGFAULT)
	152 - test_tangent_linear_ClearSky_atms_npp (SEGFAULT)
	153 - test_tangent_linear_ClearSky_cris399_npp (SEGFAULT)
	154 - test_tangent_linear_ClearSky_v.abi_gr (SEGFAULT)
	155 - test_tangent_linear_ClearSky_abi_g18 (SEGFAULT)
	156 - test_tangent_linear_ClearSky_modis_aqua (SEGFAULT)
	157 - test_forward_OMPoverChannels_atms_npp (SEGFAULT)
Errors while running CTest
```

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
This PR is fixing the `Quiet` definition inside `src/CRTM_LifeCycle.f90`.

## Issue(s) addressed
Resolves https://github.com/JCSDA/CRTMv3/issues/78

## Dependencies
None.

## Impact
None.

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by fabiolrdiniz** [comment]
@BenjaminTJohnson, please, adjust the base branch to the release branch if you prefer.

File: src/CRTM_LifeCycle.f90 [hunk 1]
```diff
@@ -632,16 +632,14 @@ FUNCTION CRTM_Init( &
...
+    INTEGER :: iQuiet ! TODO: iQuiet should be removed once load routine interfaces have been modified
+    Quiet_ = .FALSE.
+    IF ( PRESENT(Quiet) ) Quiet_ = Quiet
     iQuiet = 0
-    IF ( PRESENT(Quiet) ) THEN
-      IF ( Quiet ) THEN
-        iQuiet = 1  ! Set
-      END IF
+    IF ( Quiet_ ) THEN
+      iQuiet = 1
```
Comment (chengdang) [inline src/CRTM_LifeCycle.f90:641]: I feel the modified code and the original code are exactly the same functionality?

File: src/CRTM_LifeCycle.f90 [hunk 2]
```diff
@@ -764,7 +762,7 @@ FUNCTION CRTM_Init( &
     IF (Default_TauCoeff_Format == 'netCDF' ) THEN
         netCDF = .TRUE.
     END IF
-    IF (PRESENT(Quiet) .AND. (.NOT. Quiet)) THEN
+    IF ( .NOT. Quiet_ ) THEN
```
Comment (chengdang) [inline src/CRTM_LifeCycle.f90:765]: Are these if statements triggering the Segmentation fault?

**Review by BenjaminTJohnson — APPROVED** [review]

File: src/CRTM_LifeCycle.f90 (hunk 1 above)
Comment (chengdang) [reply src/CRTM_LifeCycle.f90:641]: NVMD, I see the need of a logical variable.

**Review by chengdang — APPROVED** [review]
Tested and it fixed most ctest failures reported in issue #78 

The following channel subset tests still fails occasionally:
```
	 34 - test_forward_ChannelSubset_iasi_metop-b (Failed)
	 90 - test_k_matrix_ChannelSubset_iasi_metop-b (Failed)
```
Will look into this in a separate issue.

File: src/CRTM_LifeCycle.f90 (hunk 1 above)
Comment (fabiolrdiniz) [reply src/CRTM_LifeCycle.f90:641]: Yes. I kept the `iQuiet` variable to keep the original code (there was a comment inside the source code saying to remove that dependency when revamping the load routines).

File: src/CRTM_LifeCycle.f90 (hunk 2 above)
Comment (fabiolrdiniz) [reply src/CRTM_LifeCycle.f90:765]: Yes.
